on:
  workflow_call: 

jobs:
  build:
    uses: ./.github/workflows/build.yml
    name: build application

  deploy:
    uses: ./.github/workflows/deploy.yml
    name: deploy application
    needs: build
